config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#root'

	resources :users, only: [:create, :new]
	resource :session, only: [:new, :create, :destroy]

	namespace :api, defaults: {format: :json} do
    resources :jobs, only: [:index, :show, :create]
    resources :myjobs, only: [:index, :show, :create, :destroy, :update]
    resources :locations, only:[:index, :show, :create]
    resource  :session, only: [:show, :create, :destroy]
  	resources :users, only: [:create, :new, :show]
    resource :users, only: [:update]
    resources :applications, only: [:index, :show, :create]
  end

  get "auth/facebook/callback", to: "omniauth#facebook"
end

app/models/user.rb
class User < ActiveRecord::Base
	# validates :email, :password_digest, :session_token, presence: true
	validates :email, :session_token, presence: true
	validates :email, :session_token, uniqueness: true
	validates :password, length: { minimum: 6, allow_nil: true }

	has_attached_file :resume, default_url: "missing.pdf"
	validates_attachment_content_type :resume, :content_type => ['application/pdf']

	has_many(
	 	:jobs,
	 	class_name: "Job",
	 	primary_key: :id,
	 	foreign_key: :employer_id
 	)
	has_many(
	  :myjobs,
	  class_name: "Myjob",
	  primary_key: :id,
	  foreign_key: :seeker_id
  )
	has_many(
	  :applications,
	  class_name: "Application",
	  primary_key: :id,
	  foreign_key: :user_id
  )
	has_many(
		:received_applications,
		through: :jobs,
		source: :applications
	)

	after_initialize :ensure_session_token!
	attr_reader :password

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def is_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
		return nil unless user && user.is_password?(password)
		user
  end

	def self.find_or_create_by_auth_hash(auth_hash)
	  provider = auth_hash[:provider]
	  uid = auth_hash[:uid]
	  user = User.find_by(provider: provider, uid: uid)
	  return user if user

	  User.create(
	    provider: provider,
	    uid: uid,
	    email: auth_hash[:extra][:raw_info][:email]
	  )
	end

	def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
	def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      render json: @user
    else
      render json: {message: @user.errors.full_messages }, status: 401
    end
  end

	def update
		@user = current_user
		if @user.update(user_params)
			  render :show
    else
			render json: @user.errors.full_messages, status: :unprocessable_entity
		end
	end


	def show
		@user = User.find(params[:id])
		render :show
	end

  def user_params
    params.require(:user).permit(:email, :password, :real_name, :phone_number, :resume)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end


  def user_params
    params.require(:user).permit(:email, :password, :real_name, :phone_number)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<label class="logo"><%= link_to "", root_url %></label>

<main class="main">
	<section class="content group">
		<section class="signin-block group">
			<section class="main-signin">
				<h2 class="signin-title">Create an account</h2>
					Already have an account? <%= link_to "Sign In", new_session_url %>
				<form action=" <%=users_url%>" method="post">
				  <%= auth_token_input %>

					<div class="input-block">
					  <label>Email Address<br />
					    <input class="input-field" type="text" name="user[email]" value="" />
					  </label>
					  <label>Password<br />
					    <input class="input-field" type="password" name="user[password]" value="" />
					  </label>
					</div>


				  <input class="signin-button" type="submit" value="Create Account" />


				</form>
			</section>
			<section class="facebook-signin">
				<button class="facebook-button">Sign in with Facebook</button>

			</section>
		</section>

	</section>
</main>